<#
.SYNOPSIS
    Creates the lab's Kubernetes Secrets from an untracked local file, and
    deliberately creates one leaky ConfigMap so the secret-sprawl weakness is
    real rather than described.

.DESCRIPTION
    Why this is a script and not a committed manifest: a Secret committed to git
    is a Secret in every clone. The value of this lab does not include teaching
    that, so values come from secrets\credentials.yaml, which .gitignore excludes.

    What it deliberately gets wrong, on purpose:

      SP-01 / T1552.001 -- the same database password is written into a ConfigMap
      named app-config-leak. ConfigMaps are world-readable to anyone holding
      `get configmaps`, which is a far more commonly granted permission than
      `get secrets`. Copying a password out of a Secret into a ConfigMap to "make
      the setup easier" is one of the most common real ways credentials leak, and
      it leaves no trace in any audit log.

    The leak is created here rather than in a manifest for exactly that reason: a
    manifest in git would be a committed password, which would make the whole
    exercise self-defeating.

.PARAMETER Force
    Regenerate values, discarding whatever is in secrets\credentials.yaml.

.EXAMPLE
    .\cluster\bootstrap\secrets.ps1
    .\cluster\bootstrap\secrets.ps1 -Force
#>
[CmdletBinding()]
param(
    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

$repoRoot   = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSCommandPath))
$template   = Join-Path $repoRoot 'secrets\credentials.example.yaml'
$localFile  = Join-Path $repoRoot 'secrets\credentials.yaml'

# ---------------------------------------------------------------------------
# Password generation
#
# Limited to an alphanumeric alphabet on purpose. A random password containing
# quotes, backslashes or newlines is correct, and then it has to be escaped
# correctly in three places: a Secret's base64, a ConfigMap's YAML, and a
# connection string inside another ConfigMap. The escaping bug is a real risk and
# it buys nothing here -- these are throwaway lab credentials, and a real
# deployment would use a sealed-secret controller instead of a PowerShell script.
# ---------------------------------------------------------------------------
function New-LabPassword {
    param([int] $Length = 24)
    $alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789'
    $bytes = New-Object 'byte[]' $Length
    # Create()/GetBytes() rather than the static ::Fill(). ::Fill was added in
    # .NET Core and is absent from .NET Framework 4.x, which is what Windows
    # PowerShell 5.1 runs on. The static call fails silently under
    # $ErrorActionPreference = 'Continue' and yields an empty password, which is
    # worse than failing loudly: the Secret gets created and the database starts.
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }
    $result = -join ($bytes | ForEach-Object { $alphabet[$_ % $alphabet.Length] })
    if ($result.Length -ne $Length) {
        throw "New-LabPassword produced $($result.Length) characters, expected $Length"
    }
    $result
}

function New-LabLocalFile {
    if (-not (Test-Path -LiteralPath $localFile)) {
        Write-Host "secrets: no local credentials file, generating one" -ForegroundColor Cyan
    } else {
        Write-Host "secrets: local credentials file found" -ForegroundColor Cyan
    }
    $content = @"
# Generated by cluster\bootstrap\secrets.ps1 -- NOT committed (see .gitignore).
# Regenerate with: .\cluster\bootstrap\secrets.ps1 -Force
postgres:
  password: "$(New-LabPassword)"
  legacy_password: "$(New-LabPassword 12)"
build:
  token: "$(New-LabPassword 32)"
"@
    # Exclusive creation so a -Force run cannot silently clobber a file another
    # terminal is reading.
    $stream = [System.IO.File]::Open(
        $localFile, [System.IO.FileMode]::CreateNew, [System.IO.FileAccess]::Write)
    try {
        $writer = [System.IO.StreamWriter]::new($stream)
        $writer.Write($content)
        $writer.Flush()
    } finally {
        $stream.Dispose()
    }
}

if ($Force -and (Test-Path -LiteralPath $localFile)) {
    Remove-Item -LiteralPath $localFile -Force
}
if (-not (Test-Path -LiteralPath $localFile)) {
    New-LabLocalFile
}

# ---------------------------------------------------------------------------
# Read values
#
# A deliberately small parser: three scalar keys, one nesting level. Pulling in a
# YAML library for this would add a dependency to a repo whose whole point is
# that it has none.
# ---------------------------------------------------------------------------
$values = @{}
$section = $null
foreach ($line in Get-Content -LiteralPath $localFile) {
    if ($line -match '^\s*#' -or $line.Trim() -eq '') { continue }
    if ($line -match '^([A-Za-z_][A-Za-z0-9_]*):\s*$') { $section = $Matches[1]; continue }
    if ($line -match '^\s+([A-Za-z_][A-Za-z0-9_]*):\s*"?([^"]*)"?\s*$') {
        $values["$section.$($Matches[1])"] = $Matches[2]
    }
}

$required = @('postgres.password', 'postgres.legacy_password', 'build.token')
$missing  = $required | Where-Object { -not $values.ContainsKey($_) -or -not $values[$_] }
if ($missing) {
    Write-Host "secrets: FAILED - missing or empty: $($missing -join ', ')" -ForegroundColor Red
    Write-Host "         delete secrets\credentials.yaml and re-run to regenerate" -ForegroundColor Red
    exit 1
}
$unreplaced = $required | Where-Object { $values[$_] -match '^REPLACE_ME$' }
if ($unreplaced) {
    Write-Host "secrets: FAILED - still placeholders: $($unreplaced -join ', ')" -ForegroundColor Red
    exit 1
}

$dbPassword = $values['postgres.password']
$dbLegacy   = $values['postgres.legacy_password']
$buildToken = $values['build.token']

function ConvertTo-Base64Utf8 {
    param([string] $Text)
    [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($Text))
}

# ---------------------------------------------------------------------------
# kubectl wrapper that actually checks whether the call worked.
#
# $ErrorActionPreference = 'Continue' is required for the progress output
# kubectl writes to stderr, which PowerShell would otherwise turn into a
# terminating error. The cost is that a genuine failure is just another line of
# stderr and the script sails on. Checking $LASTEXITCODE closes that gap: without
# it this script reported "created" for a Secret that had in fact failed.
# ---------------------------------------------------------------------------
function Invoke-Kubectl {
    param(
        [Parameter(Mandatory)] [string] $Description,
        [Parameter(Mandatory)] [string[]] $Arguments
    )
    $output = & kubectl @Arguments 2>&1
    $code   = $LASTEXITCODE
    $output | ForEach-Object { Write-Host "  $_" }
    if ($code -ne 0) {
        throw "$Description failed (kubectl exit $code)"
    }
    Write-Host "  [ok] $Description" -ForegroundColor Green
}

# Applies a rendered manifest from a temp file rather than via stdin.
#
# `kubectl apply -f -` inside a function means piping PowerShell strings into a
# native command's stdin, which re-encodes as UTF-16LE in some hosts and yields
# a baffling "error converting YAML to JSON". A temp file has no such ambiguity,
# and it leaves the exact bytes on disk if something needs re-checking.
function Invoke-KubectlManifest {
    param(
        [Parameter(Mandatory)] [string] $Description,
        [Parameter(Mandatory, ValueFromPipeline)] [string] $Yaml
    )
    begin { $buffer = [System.Text.StringBuilder]::new() }
    process { [void]$buffer.AppendLine($Yaml) }
    end {
        $temp = Join-Path ([System.IO.Path]::GetTempPath()) ("ztsoc-" + [System.IO.Path]::GetRandomFileName() + ".yaml")
        [System.IO.File]::WriteAllText($temp, $buffer.ToString(), (New-Object System.Text.UTF8Encoding($false)))
        try {
            Invoke-Kubectl -Description $Description -Arguments @('apply', '-f', $temp)
        } finally {
            Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
        }
    }
}

# ---------------------------------------------------------------------------
# Prerequisites
#
# Creating a Secret in a namespace that does not exist fails, and it fails with
# an error that does not obviously mean "apply identities/ first". Check up front
# and say so in those words.
# ---------------------------------------------------------------------------
$missingNamespaces = @('zerotrust', 'zerotrust-build') |
    Where-Object { -not ((& kubectl get namespace $_ -o name 2>$null) -match '^namespace') }
if ($missingNamespaces) {
    Write-Host "secrets: FAILED - namespace(s) not found: $($missingNamespaces -join ', ')" -ForegroundColor Red
    Write-Host "         apply the trust boundaries first:  kubectl apply -k identities" -ForegroundColor Red
    exit 1
}

# ---------------------------------------------------------------------------
# 1. The legitimate Secret
#
# Base64 is encoding, not encryption. Worth stating plainly, because "it is in a
# Secret so it is safe" is the belief that produces most cluster compromises.
# The protection a Secret actually provides is RBAC on the `secrets` resource and
# the fact that etcd holds it at rest. Anyone who can `get secret` reads it.
# ---------------------------------------------------------------------------
Write-Host "`n[1/3] applying Secret/zerotrust/postgres-credentials" -ForegroundColor Cyan
$postgresSecretYaml = & kubectl create secret generic postgres-credentials `
    --namespace zerotrust `
    --dry-run=client -o yaml `
    --from-literal=password=$dbPassword `
    --from-literal=legacy_password=$dbLegacy `
    --from-literal=username=orders
if ($LASTEXITCODE -ne 0) { throw "could not render postgres-credentials (kubectl exit $LASTEXITCODE)" }
$postgresSecretYaml | Invoke-KubectlManifest -Description 'Secret/zerotrust/postgres-credentials'

Write-Host "`n[2/3] applying Secret/zerotrust-build/build-credentials" -ForegroundColor Cyan
$buildSecretYaml = & kubectl create secret generic build-credentials `
    --namespace zerotrust-build `
    --dry-run=client -o yaml `
    --from-literal=token=$buildToken
if ($LASTEXITCODE -ne 0) { throw "could not render build-credentials (kubectl exit $LASTEXITCODE)" }
$buildSecretYaml | Invoke-KubectlManifest -Description 'Secret/zerotrust-build/build-credentials'

# ---------------------------------------------------------------------------
# 2. SP-01: the deliberate leak
#
# The same password, in a ConfigMap, in plaintext, readable by a much broader set
# of identities. Detection DET-0002 exists to catch exactly this shape.
# ---------------------------------------------------------------------------
Write-Host "`n[3/3] applying ConfigMap/zerotrust/app-config-leak  (intentional weakness SP-01)" -ForegroundColor Yellow

$leakYaml = @"
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-leak
  namespace: zerotrust
  annotations:
    zerotrust.lab/weakness: SP-01
    zerotrust.lab/attack-id: T1552.001
  labels:
    zerotrust.lab/intentional: "true"
data:
  # Copied out of Secret/postgres-credentials so the build pipeline "did not need
  # secret access". This is the mistake, and it is an ordinary one.
  DATABASE_URL: "postgresql://orders:$dbPassword@postgres.zerotrust.svc.cluster.local:5432/acme"
  DB_PASSWORD: "$dbPassword"
  NOTE: "intentional weakness SP-01 - plaintext credential in a ConfigMap"
"@
$leakYaml | Invoke-KubectlManifest -Description 'ConfigMap/zerotrust/app-config-leak  (intentional SP-01)'

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
Write-Host "`nsecrets: done." -ForegroundColor Green
Write-Host "  created  Secret/zerotrust/postgres-credentials" -ForegroundColor Green
Write-Host "  created  Secret/zerotrust-build/build-credentials" -ForegroundColor Green
Write-Host "  created  ConfigMap/zerotrust/app-config-leak  <- SP-01, intentional" -ForegroundColor Yellow
Write-Host "  source   secrets\credentials.yaml  (gitignored, never commit)" -ForegroundColor Green
Write-Host ""
Write-Host "  next: apply the workloads that consume these" -ForegroundColor Cyan
